name: GitHub CI

on: [push]

env:
  CC_TEST_REPORTER_ID: 970bebaf9e240aaf9c86a92251b68f30d373d29f4d07f2e92a0d777009c28a68
  JACOCO_SOURCE_PATH: 'interpreter.common interpreter.lacast interpreter.maple interpreter.mathematica interpreter.evaluation'

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Repo
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Codeclimate Reports
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Prepare Elasticsearch Install
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Setup Elasticsearch instance
        uses: getong/elasticsearch-action@v1.2
        with:
          elasticsearch version: '7.9.1'
          host port: 9200
          container port: 9200
          host node port: 9300
          node port: 9300
          discovery type: 'single-node'
      - name: Maven Install
        run: |
          mvn -Pbuild install -DskipTests -B -V -DgenerateJars
          java -jar bin/lexicon-creator.jar -all
      - name: Maven Test
        run: mvn test -B -DjacocoReport=remote
      - name: Fix Jacoco Reports
        run: source .github/fix-jacoco.sh
      - name: Report test coverage to Codeclimate
        run: |
          ./cc-test-reporter format-coverage ./target/jacoco-report/jacoco-fix.xml --input-type jacoco > jacoco.log 2>&1
          ./cc-test-reporter upload-coverage -d > jacocoUpload.log 2>&1
