#!/usr/bin/env bash

CONFIGFILEBASE="config/symbolic_tests-base.properties"
CONFIGFILE="config/symbolic_tests.properties"
SETFILES="config/together-lines.txt"

OUTPUTPATH="dlmf/results-generated"

if [[ -z "${LD_LIBRARY_PATH}" ]]; then
    echo "ERROR: You did not set LD_LIBRARY_PATH. But this is necessary for both CAS: Maple and Mathematica"
    exit
fi

usage() {
    echo "You must specify the CAS you want to translate to.
The following arguments are possible"
    echo ""
    echo "./lacast-eval-symbolic.sh"
    printf "\t--mathematica\tFor translations to Mathematica\n"
    printf "\t-mm\t\tAlternative for --mathematica\n"
    printf "\t--maple\t\tFor translations to Maple\n"
    printf "\t-ma\t\tAlternative for --maple\n\n"
    echo "To change the test setup, update config/symbolic_tests.properties."
}

CAS=
ARG=

while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    -mm | --mathematica)
      CAS="Mathematica"
      ARG="--mathematica"
      shift
      ;;
    -ma | --maple)
      CAS="Maple"
      ARG="--maple"
      if [[ -z "${MAPLE}" ]]; then
      	echo "ERROR: In order to use Maple, you must set the 'MAPLE' environment variable!"
      	exit;
      fi
      shift
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$CAS" ]]; then
  usage
  exit 1
fi

LACAST_LIBS="./libs"
LACAST_CLASSPATH=

for JAR in "${LACAST_LIBS}"/*.jar
do
    LACAST_CLASSPATH="${LACAST_CLASSPATH}:${JAR}"
done

NEWLINE=$'\n'
RESSTR="Results:$NEWLINE";

IFS=': '
while read line; do
  echo "Remove config file."
  rm -f $CONFIGFILE;

  echo "Create new config file."
  read -ra ADDR <<< $line;

  echo "# This file was auto-generated by 'symbolic-evaluator.sh'. Update it if you want to use 'lacast-eval-symbolic.sh'" | cat - $CONFIGFILE > temp && mv temp $CONFIGFILE
  rm temp
  cat $CONFIGFILEBASE >> $CONFIGFILE;
  
  mkdir -p "${OUTPUTPATH}/${CAS}Symbolic"
  echo "output=${OUTPUTPATH}/${CAS}Symbolic/${ADDR[0]}-symbolic.txt" >> $CONFIGFILE;
  echo "missing_macro_output=${OUTPUTPATH}/${CAS}Symbolic/${ADDR[0]}-missing.txt" >> $CONFIGFILE;
  echo "subset_tests=${ADDR[1]}" >> $CONFIGFILE;

  echo "Done creating file for ${ADDR[0]}"
  echo "Start processing..."
  java -Xmx8g -Xss200M -cp "$LACAST_CLASSPATH" gov.nist.drmf.interpreter.evaluation.core.symbolic.SymbolicEvaluator "${ARG}"
  RESULTCODE=$?;
  echo "Done ${ADDR[0]}"

  RESSTR="${RESSTR}${ADDR[0]}: $RESULTCODE $NEWLINE"
done < $SETFILES

echo "$RESSTR"
exit 0

